/* Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms. */

// Conditions 
// 1. Terms are less than four million (unsigned int)
// 2. Even terms only

#include <iostream>
using namespace std;

typedef unsigned long long ull;

int main() {
	ull solution = 0;
	int a = 1;
	int b = 1;
	int c = a + b;
	while (c < 4000000) {
		solution += c;
		a = b + c;
		b = a + c;
		c = a + b;
	}
	cout << solution << endl;
}
