/*********************************************************
Project Euler 45 (pe45.cpp)
Created by Louis Li on 2012-01-11.

PROBLEM
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
Triangle 	  	Tn=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
Pentagonal 	  	Pn=n(3n−1)/2 	  	1, 5, 12, 22, 35, ...
Hexagonal 	  	Hn=n(2n−1) 	  	1, 6, 15, 28, 45, ...

It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.

NOTES
Every hexagonal number is a triangle number (hexagonal numbers are a subset of triangle numbers)
*********************************************************/

#include <iostream>
#include "euler.h"
#include <stdint.h>

const int kHexagonalStart = 143;
int main() {
    for (int64_t n = kHexagonalStart + 1; ; n++) {
        uint64_t cand = 2 * n * n - n;
        if (euler::is_pentagonal(cand)) {
            std::cout << cand << std::endl;
            return 0;
        }
    }
}